# Generated by Django 3.1.2 on 2020-10-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discs',
            new_name='DiscsData',
        ),
    ]
